services:
 seller:
  git_url: 
  git_branch: master
  dockerfile_path: "./Dockerfile"
  build_root: seller
 buyer:
  git_url: 
  git_branch: master
  dockerfile_path: "./Dockerfile"
  build_root: buyer
